import { useState, type FormEvent } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarPlus, Plus, Save, Trash2, X } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/common/glass";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useRequireAuth } from "@/hooks/use-require-auth";
import { getEmployees } from "@/api/employees";
import { getCustomers } from "@/api/customers";
import { createOrder, type CreateOrderInput, type CreateOrderItemInput } from "@/api/orders";
import { createFollowUp } from "@/api/followups";
import { toast } from "sonner";
import { TEXTILE_UNITS } from "@/lib/constants";
import type { Customer, Order } from "@/types";

export const Route = createFileRoute("/orders/new")({ head: () => ({ meta: [{ title: "New order · Saravana Traders CRM" }] }), component: NewOrder });
const emptyItem = (): CreateOrderItemInput => ({ material: "", materialType: "General", quantity: 1, units: TEXTILE_UNITS[0] ?? "Tons", price: 0, deliveryDate: "" });
const ORDER_STATUSES = ["Confirmed", "Pending", "Cancel"] as const;

function NewOrder() {
  const user = useRequireAuth(); const navigate = useNavigate(); const queryClient = useQueryClient();
  const employeesQuery = useQuery({ queryKey: ["employees"], queryFn: getEmployees, enabled: Boolean(user) });
  const customersQuery = useQuery({ queryKey: ["customers"], queryFn: getCustomers, enabled: Boolean(user) });
  const [picked, setPicked] = useState<Customer | null>(null); const [customerSearch, setCustomerSearch] = useState(""); const [items, setItems] = useState<CreateOrderItemInput[]>([emptyItem()]);
  const [createdOrder, setCreatedOrder] = useState<Order | null>(null);
  const [followUpDate, setFollowUpDate] = useState(""); const [followUpTime, setFollowUpTime] = useState("");
  const [d, setD] = useState<Partial<CreateOrderInput>>({ orderId: "", deliveryDate: "", address: "", notes: "", status: "Pending" });
  const mutation = useMutation({ mutationFn: createOrder, onSuccess: async (order) => { await queryClient.invalidateQueries({ queryKey: ["orders"] }); await queryClient.invalidateQueries({ queryKey: ["customers"] }); setCreatedOrder(order); toast.success(`Order ${order.id} created`); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Unable to create order") });
  if (!user) return null;
  const employees = employeesQuery.data ?? []; const customers = customersQuery.data ?? []; const q = customerSearch.trim().toLowerCase(); const matches = q ? customers.filter((c) => `${c.name} ${c.company} ${c.phone}`.toLowerCase().includes(q)).slice(0, 15) : [];
  const setField = <K extends keyof CreateOrderInput>(key: K, value: CreateOrderInput[K]) => setD((p) => ({ ...p, [key]: value }));
  const updateItem = (index: number, patch: Partial<CreateOrderItemInput>) => setItems((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item));
  const total = items.reduce((sum, item) => sum + item.quantity * item.price, 0);
  const saveFollowUp = async () => { if (!createdOrder) return; if (!followUpDate || !followUpTime) { toast.error("Complete both follow-up date and time"); return; } try { await createFollowUp({ title: `Order follow-up · ${createdOrder.id}`, description: `Follow-up for order ${createdOrder.id}`, date: followUpDate, time: followUpTime, status: "Pending", priority: "Medium", reminder: false, ...(createdOrder.employeeId ? { employeeId: createdOrder.employeeId } : {}), relatedType: "Order", relatedId: createdOrder.id }); await queryClient.invalidateQueries({ queryKey: ["follow-ups"] }); toast.success("Follow-up scheduled"); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to schedule follow-up"); } };
  const submit = (e: FormEvent) => { e.preventDefault(); if (!d.orderId?.trim() || !picked || !d.deliveryDate?.trim() || !d.address?.trim() || !d.status || items.length === 0 || items.some((item) => !item.material.trim() || !item.units || !item.deliveryDate?.trim() || item.quantity <= 0 || item.price < 0)) { toast.error("Complete the order ID, customer, status, delivery details, and every item line"); return; } if ((followUpDate && !followUpTime) || (!followUpDate && followUpTime)) { toast.error("Complete both follow-up date and time"); return; } mutation.mutate({ orderId: d.orderId.trim(), customerId: picked.id, items, status: d.status, ...(user.role === "Admin" && d.employeeId ? { employeeId: d.employeeId } : {}), deliveryDate: d.deliveryDate, address: d.address.trim(), notes: d.notes?.trim() ?? "" }); };
  return <AppShell><div className="min-w-0 space-y-4"><Button variant="ghost" className="gap-2 pl-0" onClick={() => navigate({ to: "/orders" })}><ArrowLeft className="size-4" /> Back</Button><PageHeader title="Create order" subtitle="Select a customer and add one or more items" />
    <div className="glass relative z-20 overflow-visible rounded-2xl p-4"><Label>Customer</Label>{picked ? <div className="mt-1.5 flex h-10 min-w-0 items-center justify-between rounded-md glass-soft px-3 text-sm"><span className="min-w-0 truncate font-medium">{picked.name} <span className="ml-1 font-normal text-muted-foreground">· {picked.company}</span></span><button type="button" onClick={() => setPicked(null)} className="shrink-0 p-1 text-muted-foreground"><X className="size-4" /></button></div> : <div className="relative z-50 mt-1.5 min-w-0 overflow-visible"><Input value={customerSearch} onChange={(e) => setCustomerSearch(e.target.value)} placeholder="Start typing a customer name…" className="glass-soft h-10 border-0" />{matches.length > 0 && <div className="absolute top-full left-0 right-0 z-[100] mt-1 max-w-full overflow-hidden rounded-md border border-black/5 bg-white shadow-xl"><div className="max-h-[min(50vh,280px)] min-w-0 overflow-y-auto overflow-x-hidden p-1">{matches.map((c) => <button key={c.id} type="button" onClick={() => { setPicked(c); setCustomerSearch(""); setD((p) => ({ ...p, customerId: c.id, address: c.address, employeeId: c.employeeId })); }} className="flex w-full min-w-0 flex-col items-start rounded px-2 py-1.5 text-left text-sm hover:bg-mint/20"><span className="w-full truncate font-medium">{c.name} <span className="font-normal text-muted-foreground">· {c.company}</span></span><span className="w-full truncate text-[11px] text-muted-foreground">{c.phone}</span></button>)}</div></div>}</div>}</div>
    <form className="glass rounded-2xl p-4" onSubmit={submit}><p className="text-sm font-semibold">Order details</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label>Order ID</Label><Input value={d.orderId ?? ""} onChange={(e) => setField("orderId", e.target.value)} placeholder="Enter order ID" className="glass-soft h-10 border-0" required /></div><div><Label>Final delivery date</Label><Input type="date" value={d.deliveryDate ?? ""} onChange={(e) => setField("deliveryDate", e.target.value)} className="glass-soft h-10 border-0" required /></div>{user.role === "Admin" && <div><Label>Assigned employee</Label><Select value={d.employeeId ?? ""} onValueChange={(v) => setField("employeeId", v)}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue placeholder="Assign to employee" /></SelectTrigger><SelectContent>{employees.filter((e) => e.status === "Active").map((e) => <SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select></div>}<div><Label>Status</Label><Select value={d.status ?? "Pending"} onValueChange={(v) => setField("status", v as CreateOrderInput["status"])}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue placeholder="Select status" /></SelectTrigger><SelectContent>{ORDER_STATUSES.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><Label>Delivery address</Label><Input value={d.address ?? ""} onChange={(e) => setField("address", e.target.value)} className="glass-soft h-10 border-0" required /></div></div>
      <div className="mt-5 flex items-center justify-between"><p className="text-sm font-semibold">Items</p><Button type="button" variant="outline" className="gap-1.5 rounded-xl" onClick={() => setItems((current) => [...current, emptyItem()])} disabled={mutation.isPending}><Plus className="size-4" /> Add item</Button></div>
      <div className="mt-3 space-y-3">{items.map((item, index) => <div key={index} className="rounded-2xl border border-border/70 bg-white/45 p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">Item {index + 1}</p>{items.length > 1 && <Button type="button" variant="ghost" size="icon" className="text-destructive" onClick={() => setItems((current) => current.filter((_, i) => i !== index))} disabled={mutation.isPending}><Trash2 className="size-4" /></Button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Item</Label><Input value={item.material} onChange={(e) => updateItem(index, { material: e.target.value })} className="glass-soft h-10 border-0" required /></div><div><Label>Quantity</Label><Input type="number" min={1} value={item.quantity} onChange={(e) => updateItem(index, { quantity: Number(e.target.value) })} className="glass-soft h-10 border-0" required /></div><div><Label>Units</Label><Select value={item.units} onValueChange={(v) => updateItem(index, { units: v })}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue /></SelectTrigger><SelectContent>{TEXTILE_UNITS.map((u) => <SelectItem key={u} value={u}>{u}</SelectItem>)}</SelectContent></Select></div><div><Label>Unit price (₹)</Label><Input type="number" min={0} value={item.price} onChange={(e) => updateItem(index, { price: Number(e.target.value) })} className="glass-soft h-10 border-0" required /></div><div className="sm:col-span-2 lg:col-span-4"><Label>Delivery date</Label><Input type="date" value={item.deliveryDate ?? ""} onChange={(e) => updateItem(index, { deliveryDate: e.target.value })} className="glass-soft h-10 border-0" required /></div></div></div>)}</div>
      <div className="mt-5 rounded-2xl border border-border/70 bg-mint/10 p-3"><div className="mb-3 flex items-center gap-2"><CalendarPlus className="size-4 text-teal" /><p className="text-sm font-semibold">Follow-up</p></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Date</Label><Input type="date" value={followUpDate} onChange={(e) => setFollowUpDate(e.target.value)} className="glass-soft h-10 border-0" /></div><div><Label>Time</Label><Input type="time" value={followUpTime} onChange={(e) => setFollowUpTime(e.target.value)} className="glass-soft h-10 border-0" /></div></div></div>
      <div className="mt-4 sm:col-span-2"><Label>Notes</Label><Textarea rows={3} value={d.notes ?? ""} onChange={(e) => setField("notes", e.target.value)} className="glass-soft border-0" /></div>
      <div className="mt-4 flex flex-wrap items-center gap-2"><Button type="submit" disabled={mutation.isPending || customersQuery.isPending} className="gap-2 rounded-xl"><Save className="size-4" />{mutation.isPending ? "Saving..." : "Save order"}</Button><Button type="button" variant="outline" disabled={!createdOrder || mutation.isPending || !followUpDate || !followUpTime} className="gap-2 rounded-xl" onClick={() => void saveFollowUp()}><CalendarPlus className="size-4" /> Follow-up</Button>{createdOrder && <Button type="button" variant="ghost" className="rounded-xl" onClick={() => navigate({ to: "/orders/$id", params: { id: createdOrder.id } })}>View order</Button>}<Button type="button" variant="ghost" className="rounded-xl" onClick={() => navigate({ to: "/orders" })}>Cancel</Button><div className="ml-auto rounded-xl bg-mint/30 px-4 py-2 text-sm font-semibold">Total: ₹{total.toLocaleString("en-IN")}</div></div></form>
  </div></AppShell>;
}
