import { useState } from "react";
import { createFileRoute, Link, useNavigate, useParams } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarPlus, PencilLine, Trash2 } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { IdentityHeader } from "@/components/common/identity-header";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { StatusChip } from "@/components/common/status-chip";
import { Button } from "@/components/ui/button";
import { useRequireAuth } from "@/hooks/use-require-auth";
import { getOrder, deleteOrder } from "@/api/orders";
import { toast } from "sonner";
import type { Order } from "@/types";
import { canDeleteRecord, canEditRecord } from "@/lib/permissions";
import { FollowUpFormDialogApi } from "@/components/common/followup-form-dialog-api";

export const Route = createFileRoute("/orders/$id/")({ head: () => ({ meta: [{ title: "Order details · Saravana Traders CRM" }] }), component: OrderDetail });
const inr = (value: number) => `₹${value.toLocaleString("en-IN")}`;
function Field({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-white/55 px-3 py-2.5"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-0.5 break-words text-sm font-medium">{value === "" ? "—" : value}</p></div>; }
function OrderDetail() {
  const user = useRequireAuth(); const { id } = useParams({ from: "/orders/$id/" }); const navigate = useNavigate(); const queryClient = useQueryClient(); const [confirmDelete, setConfirmDelete] = useState(false); const [openFollowUp, setOpenFollowUp] = useState(false);
  const orderQuery = useQuery({ queryKey: ["orders", id], queryFn: () => getOrder(id), enabled: Boolean(user && id) });
  const deleteMutation = useMutation({ mutationFn: () => deleteOrder(id), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["orders"] }); queryClient.removeQueries({ queryKey: ["orders", id] }); setConfirmDelete(false); toast.success("Order deleted"); navigate({ to: "/orders" }); }, onError: (e) => { setConfirmDelete(false); toast.error(e instanceof Error ? e.message : "Unable to delete order"); } });
  if (!user) return null; if (orderQuery.isPending) return <AppShell><div className="glass rounded-2xl p-8 text-center text-sm text-muted-foreground">Loading order...</div></AppShell>; if (orderQuery.isError || !orderQuery.data) return <AppShell><div className="glass rounded-2xl p-8 text-center"><p className="font-medium">Order not found</p><Link to="/orders" className="mt-3 inline-block text-sm text-primary">Back to orders</Link></div></AppShell>;
  const order: Order = orderQuery.data; const canEdit = canEditRecord(user, order); const canDelete = canDeleteRecord(user, order); const items = order.items?.length ? order.items : [{ id: `OI-${order.id}`, material: order.material, materialType: order.materialType, quantity: order.quantity, units: order.units, price: order.price, value: order.value, deliveryDate: order.deliveryDate }];
  return <AppShell><div className="space-y-4"><Button variant="ghost" className="gap-2 pl-0" onClick={() => navigate({ to: "/orders" })}><ArrowLeft className="size-4" />Back</Button><IdentityHeader name={order.id} company={order.customerName} phone="" email="" meta={`Order ID ${order.id} · created ${order.createdAt}`} actions={canEdit ? <><Button variant="outline" className="glass-soft gap-2 rounded-xl border-0" onClick={() => navigate({ to: "/orders/$id/edit", params: { id: order.id } })}><PencilLine className="size-4" />Edit</Button>{canDelete && <Button variant="ghost" className="gap-2 rounded-xl text-destructive" onClick={() => setConfirmDelete(true)} disabled={deleteMutation.isPending}><Trash2 className="size-4" />Delete</Button>}</> : null} />
    <div className="grid gap-3 lg:grid-cols-3"><div className="glass rounded-2xl p-4 lg:col-span-2"><p className="text-sm font-semibold">Order information</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><Field label="Order ID" value={order.id} /><div className="rounded-xl bg-white/55 px-3 py-2.5"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">Customer</p><Link to="/customers/$id" params={{ id: order.customerId }} className="mt-0.5 block text-sm font-medium text-primary hover:underline">{order.customerName}</Link></div><Field label="Company" value={order.company} /><Field label="Total order value" value={inr(order.value)} /><Field label="Final delivery date" value={order.deliveryDate} /><Field label="Created" value={order.createdAt} /><div><p className="text-[11px] uppercase tracking-wide text-muted-foreground">Order status</p><div className="mt-1"><StatusChip value={order.status} /></div></div><Field label="Assigned employee" value={order.employeeId} /><div className="sm:col-span-2"><Field label="Delivery address" value={order.address} /></div></div><div className="mt-5"><p className="mb-2 text-sm font-semibold">Items in this order</p><div className="overflow-x-auto rounded-xl border border-border/70 bg-white/55"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="px-3 py-2">Item</th><th className="px-3 py-2">Quantity</th><th className="px-3 py-2">Units</th><th className="px-3 py-2">Unit price</th><th className="px-3 py-2">Delivery date</th><th className="px-3 py-2">Value</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="px-3 py-2 font-medium">{item.material}</td><td className="px-3 py-2">{item.quantity}</td><td className="px-3 py-2">{item.units}</td><td className="px-3 py-2">{inr(item.price)}</td><td className="px-3 py-2">{item.deliveryDate || "—"}</td><td className="px-3 py-2">{inr(item.value)}</td></tr>)}</tbody><tfoot><tr><td colSpan={5} className="px-3 py-2 text-right font-semibold">Total</td><td className="px-3 py-2 font-semibold">{inr(order.value)}</td></tr></tfoot></table></div></div><div className="mt-4"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">Notes</p><p className="mt-1 rounded-xl bg-white/55 px-3 py-2.5 text-sm whitespace-pre-wrap">{order.notes || "No notes added."}</p></div></div><div className="space-y-3"><div className="glass rounded-2xl p-4"><p className="text-sm font-semibold">Order summary</p><div className="mt-3 space-y-2"><Field label="Order ID" value={order.id} /><Field label="Customer" value={order.customerName} /><Field label="Items" value={items.length} /><Field label="Total value" value={inr(order.value)} /></div><Button className="mt-3 w-full gap-2 rounded-xl" onClick={() => setOpenFollowUp(true)}><CalendarPlus className="size-4" />Add Follow-up</Button></div></div></div>
    <ConfirmDialog open={confirmDelete} onOpenChange={setConfirmDelete} title={`Delete ${order.id}?`} description="This order will be permanently deleted." confirmLabel={deleteMutation.isPending ? "Deleting..." : "Delete order"} destructive onConfirm={() => deleteMutation.mutate()} /><FollowUpFormDialogApi open={openFollowUp} onOpenChange={setOpenFollowUp} target={{ id: order.id, name: order.id, type: "Order" }} />
  </div></AppShell>;
}
