import { useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarPlus, Plus, Save, Trash2, X } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/common/glass";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useRequireAuth } from "@/hooks/use-require-auth";
import { getEmployees } from "@/api/employees";
import { getCustomers } from "@/api/customers";
import { createOrder, type CreateOrderInput, type CreateOrderItemInput } from "@/api/orders";
import { toast } from "sonner";
import { TEXTILE_TYPES, TEXTILE_UNITS } from "@/lib/constants";
import type { Customer, OrderStatus, PaymentStatus } from "@/types";
export const Route = createFileRoute("/orders/new")({ head: () => ({ meta: [{ title: "New order · Saravana Traders CRM" }] }), component: NewOrder });
const STATUSES: OrderStatus[] = ["Draft", "Confirmed", "Processing", "Packed", "Dispatched", "Delivered", "Cancelled"];
const PAYMENTS: PaymentStatus[] = ["Pending", "Partial", "Paid"];
const emptyItem = (): CreateOrderItemInput => ({ material: "", materialType: TEXTILE_TYPES[0] ?? "Grey Fabric", quantity: 1, units: TEXTILE_UNITS[0] ?? "Tons", price: 0 });
function NewOrder() {
  const user = useRequireAuth(); const navigate = useNavigate(); const queryClient = useQueryClient();
  const employeesQuery = useQuery({ queryKey: ["employees"], queryFn: getEmployees, enabled: Boolean(user) }); const customersQuery = useQuery({ queryKey: ["customers"], queryFn: getCustomers, enabled: Boolean(user) });
  const [picked, setPicked] = useState<Customer | null>(null); const [customerSearch, setCustomerSearch] = useState(""); const [items, setItems] = useState<CreateOrderItemInput[]>([emptyItem()]);
  const [d, setD] = useState<Partial<CreateOrderInput>>({ paymentStatus: "Pending", status: "Draft", invoiceNumber: "", deliveryDate: "", address: "", notes: "" });
  const mutation = useMutation({ mutationFn: createOrder, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["orders"] }); await queryClient.invalidateQueries({ queryKey: ["customers"] }); toast.success("Order created"); navigate({ to: "/orders" }); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Unable to create order") });
  if (!user) return null; const employees = employeesQuery.data ?? []; const customers = customersQuery.data ?? []; const q = customerSearch.trim().toLowerCase(); const matches = q ? customers.filter((c) => `${c.name} ${c.company} ${c.phone}`.toLowerCase().includes(q)).slice(0, 15) : [];
  const setField = (key: keyof CreateOrderInput, value: never) => setD((p) => ({ ...p, [key]: value }));
  const updateItem = (index: number, patch: Partial<CreateOrderItemInput>) => setItems((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item));
  const total = items.reduce((sum, item) => sum + item.quantity * item.price, 0);
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!picked || !d.deliveryDate?.trim() || !d.address?.trim() || items.some((item) => !item.material.trim() || !item.materialType || !item.units || item.quantity <= 0 || item.price < 0)) { toast.error("Complete the customer, delivery details, and every material line"); return; } mutation.mutate({ invoiceNumber: d.invoiceNumber?.trim() || "ST/26-27/TEMP", customerId: picked.id, items, paymentStatus: d.paymentStatus ?? "Pending", status: d.status ?? "Draft", ...(user.role === "Admin" && d.employeeId ? { employeeId: d.employeeId } : {}), deliveryDate: d.deliveryDate, address: d.address.trim(), notes: d.notes?.trim() ?? "" }); };
  return <AppShell><div className="space-y-4"><Button variant="ghost" className="gap-2 pl-0" onClick={() => navigate({ to: "/orders" })}><ArrowLeft className="size-4" /> Back</Button><PageHeader title="Create order" subtitle="Select a customer and add one or more materials" />
    <div className="glass rounded-2xl p-4"><Label>Customer</Label>{picked ? <div className="mt-1.5 flex h-10 items-center justify-between rounded-md glass-soft px-3 text-sm"><span className="truncate font-medium">{picked.name} <span className="ml-1 font-normal text-muted-foreground">· {picked.company}</span></span><button type="button" onClick={() => setPicked(null)} className="p-1 text-muted-foreground"><X className="size-4" /></button></div> : <div className="relative mt-1.5"><Input value={customerSearch} onChange={(e) => setCustomerSearch(e.target.value)} placeholder="Start typing a customer name…" className="glass-soft h-10 border-0" />{matches.length > 0 && <div className="absolute top-full left-0 z-50 mt-1 w-full overflow-hidden rounded-md border bg-white shadow-md"><div className="max-h-60 overflow-y-auto p-1">{matches.map((c) => <button key={c.id} type="button" onClick={() => { setPicked(c); setCustomerSearch(""); setD((p) => ({ ...p, customerId: c.id, address: c.address, employeeId: c.employeeId })); }} className="flex w-full flex-col items-start rounded px-2 py-1.5 text-left text-sm hover:bg-mint/20"><span className="font-medium">{c.name} <span className="font-normal text-muted-foreground">· {c.company}</span></span><span className="text-[11px] text-muted-foreground">{c.phone}</span></button>)}</div></div>}</div>}</div>
    <form className="glass rounded-2xl p-4" onSubmit={submit}><p className="text-sm font-semibold">Order details</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label>Invoice number</Label><Input value={d.invoiceNumber ?? ""} onChange={(e) => setField("invoiceNumber", e.target.value as never)} className="glass-soft h-10 border-0" /></div><div><Label>Delivery date</Label><Input type="date" value={d.deliveryDate ?? ""} onChange={(e) => setField("deliveryDate", e.target.value as never)} className="glass-soft h-10 border-0" required /></div>{user.role === "Admin" && <div><Label>Assigned employee</Label><Select value={d.employeeId ?? ""} onValueChange={(v) => setField("employeeId", v as never)}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue placeholder="Assign to employee" /></SelectTrigger><SelectContent>{employees.filter((e) => e.status === "Active").map((e) => <SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select></div>}<div className="sm:col-span-2"><Label>Delivery address</Label><Input value={d.address ?? ""} onChange={(e) => setField("address", e.target.value as never)} className="glass-soft h-10 border-0" required /></div></div>
      <div className="mt-5 flex items-center justify-between"><p className="text-sm font-semibold">Materials</p><Button type="button" variant="outline" className="gap-1.5 rounded-xl" onClick={() => setItems((current) => [...current, emptyItem()])}><Plus className="size-4" /> Add material</Button></div>
      <div className="mt-3 space-y-3">{items.map((item, index) => <div key={index} className="rounded-2xl border border-border/70 bg-white/45 p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">Material {index + 1}</p>{items.length > 1 && <Button type="button" variant="ghost" size="icon" className="text-destructive" onClick={() => setItems((current) => current.filter((_, i) => i !== index))}><Trash2 className="size-4" /></Button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Material</Label><Input value={item.material} onChange={(e) => updateItem(index, { material: e.target.value })} className="glass-soft h-10 border-0" required /></div><div><Label>Type</Label><Select value={item.materialType} onValueChange={(v) => updateItem(index, { materialType: v })}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue /></SelectTrigger><SelectContent>{TEXTILE_TYPES.map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantity</Label><Input type="number" min={1} value={item.quantity} onChange={(e) => updateItem(index, { quantity: Number(e.target.value) })} className="glass-soft h-10 border-0" required /></div><div><Label>Units</Label><Select value={item.units} onValueChange={(v) => updateItem(index, { units: v })}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue /></SelectTrigger><SelectContent>{TEXTILE_UNITS.map((u) => <SelectItem key={u} value={u}>{u}</SelectItem>)}</SelectContent></Select></div><div><Label>Unit price (₹)</Label><Input type="number" min={0} value={item.price} onChange={(e) => updateItem(index, { price: Number(e.target.value) })} className="glass-soft h-10 border-0" required /></div><div className="flex items-end"><div className="w-full"><Label>Line value</Label><div className="glass-soft flex h-10 items-center rounded-md px-3 text-sm font-semibold">₹{(item.quantity * item.price).toLocaleString("en-IN")}</div></div></div></div></div>)}</div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><div><Label>Status</Label><Select value={d.status ?? "Draft"} onValueChange={(v) => setField("status", v as never)}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue /></SelectTrigger><SelectContent>{STATUSES.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><div><Label>Payment status</Label><Select value={d.paymentStatus ?? "Pending"} onValueChange={(v) => setField("paymentStatus", v as never)}><SelectTrigger className="glass-soft h-10 w-full border-0"><SelectValue /></SelectTrigger><SelectContent>{PAYMENTS.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><Label>Notes</Label><Textarea rows={3} value={d.notes ?? ""} onChange={(e) => setField("notes", e.target.value as never)} className="glass-soft border-0" /></div></div>
      <div className="mt-4 flex flex-wrap items-center gap-2"><Button type="submit" disabled={mutation.isPending || customersQuery.isPending} className="gap-2 rounded-xl"><Save className="size-4" />{mutation.isPending ? "Saving..." : "Save order"}</Button><Button type="button" variant="ghost" className="rounded-xl" onClick={() => navigate({ to: "/orders" })}>Cancel</Button><div className="ml-auto rounded-xl bg-mint/30 px-4 py-2 text-sm font-semibold">Total: ₹{total.toLocaleString("en-IN")}</div></div></form>
  </div></AppShell>;
}
