import { useState, useMemo, useEffect, useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import { Search, X } from "lucide-react";
import { Input } from "@/components/ui/input";
import { getCustomers } from "@/api/customers";
import { getLeads } from "@/api/leads";
import type { Customer, Lead } from "@/types";

export type SearchRecord = (Customer | Lead) & { type: "Customer" | "Lead" };
interface CustomerLeadSearchProps { value?: string | null; onChange: (value: string | null, record?: SearchRecord) => void; placeholder?: string; typeFilter?: "Customer" | "Lead" | "Both"; }
export function CustomerLeadSearch({ value, onChange, placeholder = "Search customer or lead...", typeFilter = "Both" }: CustomerLeadSearchProps) {
  const [query, setQuery] = useState(""); const [isOpen, setIsOpen] = useState(false); const containerRef = useRef<HTMLDivElement>(null);
  const customersQuery = useQuery({ queryKey: ["customers"], queryFn: getCustomers, enabled: typeFilter !== "Lead" }); const leadsQuery = useQuery({ queryKey: ["leads"], queryFn: getLeads, enabled: typeFilter !== "Customer" });
  const allRecords: SearchRecord[] = useMemo(() => [...(typeFilter !== "Lead" ? (customersQuery.data ?? []).map((c) => ({ ...c, type: "Customer" as const })) : []), ...(typeFilter !== "Customer" ? (leadsQuery.data ?? []).map((l) => ({ ...l, type: "Lead" as const })) : [])], [customersQuery.data, leadsQuery.data, typeFilter]);
  const selectedRecord = useMemo(() => value ? allRecords.find((r) => r.id === value) ?? null : null, [value, allRecords]);
  const matches = useMemo(() => { const lower = query.trim().toLowerCase(); if (!lower) return []; return allRecords.map((record) => { const n = record.name.toLowerCase(); const c = record.company.toLowerCase(); const p = record.phone.toLowerCase(); const score = n.startsWith(lower) ? 3 : n.includes(lower) ? 2 : c.includes(lower) || p.includes(lower) ? 1 : 0; return { record, score }; }).filter((s) => s.score > 0).sort((a, b) => b.score - a.score).map((s) => s.record).slice(0, 15); }, [query, allRecords]);
  useEffect(() => { const handle = (e: MouseEvent) => { if (containerRef.current && !containerRef.current.contains(e.target as Node)) setIsOpen(false); }; document.addEventListener("mousedown", handle); return () => document.removeEventListener("mousedown", handle); }, []);
  if (selectedRecord) return <div className="relative w-full max-w-full min-w-0"><div className="flex h-10 w-full min-w-0 items-center justify-between rounded-md border-0 glass-soft px-3 pr-2 shadow-sm text-sm"><div className="min-w-0 flex-1 truncate font-medium">{selectedRecord.name} <span className="text-muted-foreground font-normal ml-1">· {selectedRecord.company}</span></div><button type="button" className="shrink-0 p-1 hover:bg-black/5 rounded-full text-muted-foreground" onClick={() => { onChange(null); setQuery(""); }}><X className="h-4 w-4" /></button></div></div>;
  return <div className="relative w-full max-w-full min-w-0" ref={containerRef}><div className="relative min-w-0"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground shrink-0" /><Input type="text" value={query} onChange={(e) => { setQuery(e.target.value); setIsOpen(true); }} onFocus={() => setIsOpen(true)} placeholder={placeholder} className="h-10 w-full max-w-full glass-soft border-0 pl-9" /></div>{isOpen && matches.length > 0 && <div className="absolute top-full left-0 right-0 z-50 mt-1 max-w-full overflow-hidden rounded-md border border-black/5 bg-white shadow-md"><div className="max-h-[min(50vh,240px)] min-w-0 overflow-y-auto overflow-x-hidden p-1">{matches.map((r) => <button key={`${r.type}-${r.id}`} type="button" onClick={() => { onChange(r.id, r); setIsOpen(false); setQuery(""); }} className="flex w-full min-w-0 flex-col items-start rounded-sm px-2 py-1.5 text-left text-sm hover:bg-mint/20 focus:bg-mint/20 focus:outline-none"><div className="w-full min-w-0 truncate font-medium text-gray-900">{r.name} <span className="text-gray-500 font-normal">· {r.company}</span></div>{typeFilter === "Both" && <div className="text-[11px] font-medium text-teal-700/70 mt-0.5">{r.type}</div>}</button>)}</div></div>}</div>;
}
