import { useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { CalendarPlus, Check, ChevronRight, Pencil, Trash2 } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { StatusChip } from "@/components/common/status-chip";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { FollowUpFormDialogApi, type FollowUpTarget } from "@/components/common/followup-form-dialog-api";
import { getFollowUps, completeFollowUp, deleteFollowUp } from "@/api/followups";
import { getEmployees } from "@/api/employees";
import { useRequireAuth } from "@/hooks/use-require-auth";
import { cn } from "@/lib/utils";
import type { FollowUp } from "@/types";

function sortChrono(items: FollowUp[]) { return [...items].sort((a, b) => `${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)); }

export function FollowUpTimeline({ items, target, title = "Follow-up history" }: { items: FollowUp[]; target: FollowUpTarget; title?: string }) {
  const user = useRequireAuth(); const queryClient = useQueryClient(); const navigate = useNavigate();
  const [detail, setDetail] = useState<FollowUp | null>(null); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<FollowUp | null>(null); const [confirmDelete, setConfirmDelete] = useState(false);
  const followUpsQuery = useQuery({ queryKey: ["follow-ups"], queryFn: getFollowUps, enabled: Boolean(user) });
  const employeesQuery = useQuery({ queryKey: ["employees"], queryFn: getEmployees, enabled: Boolean(user) });
  const completeMutation = useMutation({ mutationFn: completeFollowUp, onSuccess: async (updated) => { queryClient.setQueryData<FollowUp[]>(["follow-ups"], (old) => old?.map((f) => f.id === updated.id ? updated : f)); await queryClient.invalidateQueries({ queryKey: ["follow-ups"] }); toast.success("Follow-up marked completed"); setDetail(null); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Unable to complete follow-up") });
  const deleteMutation = useMutation({ mutationFn: deleteFollowUp, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["follow-ups"] }); toast.success("Follow-up deleted"); setConfirmDelete(false); setDetail(null); }, onError: (e) => { setConfirmDelete(false); toast.error(e instanceof Error ? e.message : "Unable to delete follow-up"); } });
  const source = items.length ? items : (followUpsQuery.data ?? []).filter((f) => f.relatedType === target.type && f.relatedId === target.id);
  const ordered = sortChrono(source); const employees = employeesQuery.data ?? []; const nameOfEmployee = (id: string) => employees.find((e) => e.id === id)?.name ?? "Unassigned"; const detailIndex = detail ? ordered.findIndex((f) => f.id === detail.id) : -1; const previous = detailIndex > 0 ? ordered[detailIndex - 1] : null;
  if (!user) return null;
  return <div className="glass rounded-2xl p-4"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><p className="truncate text-sm font-semibold">{title}</p><Button size="sm" variant="ghost" className="shrink-0 gap-1.5" onClick={() => { setEditing(null); setCreating(true); }}><CalendarPlus className="size-4" /> Add</Button></div>{followUpsQuery.isPending && items.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">Loading follow-ups...</p> : followUpsQuery.isError && items.length === 0 ? <p className="mt-3 text-sm text-destructive">Unable to load follow-ups.</p> : ordered.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">No follow-ups recorded yet.</p> : <><div className="mt-3 hidden overflow-x-auto pb-2 md:block"><div className="flex items-stretch gap-2">{ordered.map((f, i) => <div key={f.id} className="flex items-center gap-2"><Card f={f} horizontal onClick={() => setDetail(f)} employeeName={nameOfEmployee(f.employeeId)} />{i < ordered.length - 1 && <ChevronRight className="size-4 shrink-0 text-primary/50" />}</div>)}</div></div><div className="mt-3 space-y-2 border-l border-border pl-4 md:hidden">{ordered.map((f) => <div key={f.id} className="relative"><span className="absolute top-4 -left-[22px] size-2.5 rounded-full bg-primary" /><Card f={f} horizontal={false} onClick={() => setDetail(f)} employeeName={nameOfEmployee(f.employeeId)} /></div>)}</div></>}
  <Dialog open={!!detail} onOpenChange={(o) => !o && setDetail(null)}><DialogContent className="w-[calc(100vw-32px)] max-h-[85vh] max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-xl">{detail && <><DialogHeader><DialogTitle className="text-left">{detail.title}</DialogTitle></DialogHeader><div className="grid gap-2 sm:grid-cols-2"><Info label="Date" value={detail.date} /><Info label="Time" value={detail.time} /><Info label="Status" value={<StatusChip value={detail.status} />} /><Info label="Priority" value={<StatusChip value={detail.priority} />} /><Info label="Assigned employee" value={<Link to="/employees/$id" params={{ id: detail.employeeId }} className="text-sm font-medium text-primary">{nameOfEmployee(detail.employeeId)}</Link>} /><Info label={detail.relatedType} value={detail.relatedName} /><div className="sm:col-span-2"><Info label="Description" value={detail.description} /></div><div className="sm:col-span-2"><Info label="Previous follow-up" value={previous ? `${previous.title} · ${previous.date}` : "This is the first follow-up."} /></div></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" className="glass-soft gap-1.5 rounded-xl border-0" onClick={() => { setEditing(detail); setDetail(null); setCreating(true); }}><Pencil className="size-3.5" /> Edit</Button><Button size="sm" className="gap-1.5 rounded-xl" disabled={detail.status === "Completed" || completeMutation.isPending} onClick={() => completeMutation.mutate(detail.id)}><Check className="size-3.5" /> {completeMutation.isPending ? "Completing..." : "Complete"}</Button><Button size="sm" variant="ghost" className="rounded-xl" onClick={() => { setDetail(null); navigate({ to: detail.relatedType === "Lead" ? "/leads/$id" : "/customers/$id", params: { id: detail.relatedId } }); }}>View {detail.relatedType}</Button><Button size="sm" variant="ghost" className="gap-1.5 rounded-xl text-destructive" onClick={() => setConfirmDelete(true)} disabled={deleteMutation.isPending}><Trash2 className="size-3.5" /> Delete</Button></div></>}</DialogContent></Dialog><ConfirmDialog open={confirmDelete} onOpenChange={setConfirmDelete} title="Delete follow-up?" description="This action cannot be undone." confirmLabel={deleteMutation.isPending ? "Deleting..." : "Delete"} destructive onConfirm={() => detail && deleteMutation.mutate(detail.id)} /><FollowUpFormDialogApi open={creating} onOpenChange={(o) => { setCreating(o); if (!o) setEditing(null); }} target={target} existing={editing} /></div>;
}
function Card({ f, horizontal, onClick, employeeName }: { f: FollowUp; horizontal: boolean; onClick: () => void; employeeName: string }) { return <button type="button" onClick={onClick} className={cn("glass-soft rounded-2xl p-3 text-left transition-colors hover:bg-mint/25", horizontal ? "w-[210px] shrink-0" : "w-full")}><p className="text-[11px] text-muted-foreground">{f.date} · {f.time}</p><p className="mt-0.5 truncate text-sm font-semibold">{f.title}</p><p className="mt-0.5 truncate text-[11px] text-muted-foreground">{employeeName}</p><p className="mt-1 line-clamp-2 text-[11px] text-muted-foreground">{f.description}</p><StatusChip value={f.status} className="mt-1.5" /></button>; }
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-xl bg-white/55 px-3 py-2"><p className="text-[11px] tracking-wide text-muted-foreground uppercase">{label}</p><div className="mt-0.5 text-sm font-medium break-words">{value}</div></div>; }
