/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersIdIndexRouteImport } from './routes/orders.$id.index'
import { Route as OrdersIdEditRouteImport } from './routes/orders.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdIndexRoute = OrdersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersIdRoute,
} as any)
const OrdersIdEditRoute = OrdersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/orders/$id/edit': typeof OrdersIdEditRoute
  '/orders/$id/': typeof OrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/orders/new': typeof OrdersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/orders/$id/edit': typeof OrdersIdEditRoute
  '/orders/$id': typeof OrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/orders/$id/edit': typeof OrdersIdEditRoute
  '/orders/$id/': typeof OrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/employees/$id'
    | '/employees/new'
    | '/leads/$id'
    | '/leads/new'
    | '/orders/$id'
    | '/orders/new'
    | '/customers/'
    | '/employees/'
    | '/leads/'
    | '/orders/'
    | '/orders/$id/edit'
    | '/orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/employees/$id'
    | '/employees/new'
    | '/leads/$id'
    | '/leads/new'
    | '/orders/new'
    | '/customers'
    | '/employees'
    | '/leads'
    | '/orders'
    | '/orders/$id/edit'
    | '/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/employees/$id'
    | '/employees/new'
    | '/leads/$id'
    | '/leads/new'
    | '/orders/$id'
    | '/orders/new'
    | '/customers/'
    | '/employees/'
    | '/leads/'
    | '/orders/'
    | '/orders/$id/edit'
    | '/orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  EmployeesIdRoute: typeof EmployeesIdRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  OrdersNewRoute: typeof OrdersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id/': {
      id: '/orders/$id/'
      path: '/'
      fullPath: '/orders/$id/'
      preLoaderRoute: typeof OrdersIdIndexRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/orders/$id/edit': {
      id: '/orders/$id/edit'
      path: '/edit'
      fullPath: '/orders/$id/edit'
      preLoaderRoute: typeof OrdersIdEditRouteImport
      parentRoute: typeof OrdersIdRoute
    }
  }
}

interface OrdersIdRouteChildren {
  OrdersIdEditRoute: typeof OrdersIdEditRoute
  OrdersIdIndexRoute: typeof OrdersIdIndexRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdEditRoute: OrdersIdEditRoute,
  OrdersIdIndexRoute: OrdersIdIndexRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  EmployeesIdRoute: EmployeesIdRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  LeadsIdRoute: LeadsIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  OrdersIdRoute: OrdersIdRouteWithChildren,
  OrdersNewRoute: OrdersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
